/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Slava Z. (https://sketchfab.com/slava)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/destructible-robot-highpoly-0f9c08f0d8d94f3a9938d4d8bf423f46
title: Destructible Robot - Highpoly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.M_Mask_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
          <mesh geometry={nodes.M_Head_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.M_Head_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
          <mesh geometry={nodes.SK_Head_Hi_Kashima_Mat_0.geometry} material={materials.Kashima_Mat} />
          <mesh geometry={nodes.SK_Head_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.SK_Head_Hi_Dark_Mat_0_1.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.SK_Head_Hi_Eyes_Mat_0.geometry} material={materials.Eyes_Mat} />
          <mesh geometry={nodes.SK_Head_Neck_Hi_Wires_Mat1_0.geometry} material={materials.Wires_Mat1} />
          <mesh geometry={nodes.SK_Head_Neck_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.M_Chest_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
          <mesh geometry={nodes.M_Chest_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.M_Chest_Hi_Kashima_Mat_0.geometry} material={materials.Kashima_Mat} />
          <mesh geometry={nodes.M_Torso_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
          <mesh geometry={nodes.M_Torso_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.M_Torso_Hi_Rubber_Mat_0.geometry} material={materials.Rubber_Mat} />
          <mesh geometry={nodes.SK_Torso_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.SK_Torso_Hi_Wires_Mat1_0.geometry} material={materials.Wires_Mat1} />
          <mesh geometry={nodes.M_Pelvis_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
          <mesh geometry={nodes.SK_Pelvis_Hi_Kashima_Mat_0.geometry} material={materials.Kashima_Mat} />
          <mesh geometry={nodes.SK_Pelvis_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.SK_Pelvis_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
          <mesh geometry={nodes.SK_Chest_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.SK_Chest_Hi_Dark_Mat_0_1.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.SK_Chest_Hi_Dark_Mat_0_2.geometry} material={materials.Dark_Mat} />
          <mesh geometry={nodes.SK_Chest_Hi_Kashima_Mat_0.geometry} material={materials.Kashima_Mat} />
          <group position={[-65.41, 25.72, -21.49]} rotation={[0.23, 0.07, -0.49]}>
            <mesh geometry={nodes.M_Arm_Upper_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
            <mesh geometry={nodes.M_Arm_Upper_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Arm_Upper_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Arm_Upper_Hi_Wires_Mat1_0.geometry} material={materials.Wires_Mat1} />
            <mesh geometry={nodes.SK_Arm_Upper_Hi_Kashima_Mat_0.geometry} material={materials.Kashima_Mat} />
            <group position={[-17.6, 13.02, 30.51]} rotation={[-0.46, -0.41, -0.15]}>
              <mesh geometry={nodes.M_Arm_Lower_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
              <mesh geometry={nodes.M_Arm_Lower_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
              <mesh geometry={nodes.M_Arm_Lower_Hi_Rubber_Mat_0.geometry} material={materials.Rubber_Mat} />
              <mesh geometry={nodes.SK_Arm_Lower_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
              <mesh geometry={nodes.SK_Arm_Lower_Hi_Rubber_Mat_0.geometry} material={materials.Rubber_Mat} />
              <mesh geometry={nodes.SK_Hand_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
              <mesh geometry={nodes.SK_Hand_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
            </group>
          </group>
          <group position={[0.09, 0, 1.55]} rotation={[0, 0.12, 0]}>
            <mesh geometry={nodes.SK_Leg_Upper_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Leg_Upper_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
            <mesh geometry={nodes.SK_Leg_Upper_Hi_Rubber_Mat_0.geometry} material={materials.Rubber_Mat} />
            <mesh geometry={nodes.M_Leg_Lower_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.M_Leg_Lower_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
            <mesh geometry={nodes.SK_Leg_Lower_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Leg_Lower_Hi_Wires_Mat1_0.geometry} material={materials.Wires_Mat1} />
            <mesh geometry={nodes.SK_Leg_Lower_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
            <mesh geometry={nodes.SK_Foot_Hi_Rubber_Mat_0.geometry} material={materials.Rubber_Mat} />
            <mesh geometry={nodes.SK_Foot_Hi_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Foot_Hi_Kashima_Mat_0.geometry} material={materials.Kashima_Mat} />
            <group position={[0.09, 0, -1.55]} rotation={[0, -0.12, 0]}>
              <mesh geometry={nodes.M_Leg_Upper_Hi2_Dark_Mat_0.geometry} material={materials.Dark_Mat} />
              <mesh geometry={nodes.M_Leg_Upper_Hi2_Body_Mat_0.geometry} material={materials.Body_Mat} />
            </group>
          </group>
          <group rotation={[0.23, 0.07, -0.49]}>
            <mesh geometry={nodes.SK_Arm_Upper_Hi_Dark_Mat_0_1.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Arm_Upper_Hi_Wires_Mat1_0_1.geometry} material={materials.Wires_Mat1} />
            <mesh geometry={nodes.SK_Arm_Upper_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
            <mesh geometry={nodes.SK_Arm_Upper_Hi_Kashima_Mat_0_1.geometry} material={materials.Kashima_Mat} />
            <group rotation={[-0.46, -0.41, -0.15]}>
              <mesh geometry={nodes.SK_Arm_Lower_Hi_Dark_Mat_0_1.geometry} material={materials.Dark_Mat} />
              <mesh geometry={nodes.SK_Arm_Lower_Hi_Body_Mat_0.geometry} material={materials.Body_Mat} />
              <mesh geometry={nodes.SK_Arm_Lower_Hi_Wires_Mat1_0.geometry} material={materials.Wires_Mat1} />
              <mesh geometry={nodes.SK_Arm_Lower_Hi_Rubber_Mat_0_1.geometry} material={materials.Rubber_Mat} />
              <mesh geometry={nodes.SK_Hand_Hi_Dark_Mat_0_1.geometry} material={materials.Dark_Mat} />
              <mesh geometry={nodes.SK_Hand_Hi_Wires_Mat1_0.geometry} material={materials.Wires_Mat1} />
              <mesh geometry={nodes.SK_Hand_Hi_Body_Mat_0_1.geometry} material={materials.Body_Mat} />
            </group>
          </group>
          <group rotation={[0, 0.12, 0]}>
            <mesh geometry={nodes.SK_Leg_Upper_Hi_Dark_Mat_0_1.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Leg_Upper_Hi_Body_Mat_0_1.geometry} material={materials.Body_Mat} />
            <mesh geometry={nodes.SK_Leg_Upper_Hi_Wires_Mat1_0.geometry} material={materials.Wires_Mat1} />
            <mesh geometry={nodes.SK_Leg_Upper_Hi_Rubber_Mat_0_1.geometry} material={materials.Rubber_Mat} />
            <mesh geometry={nodes.SK_Leg_Upper_Hi_Chrome_Mat_0.geometry} material={materials.Chrome_Mat} />
            <mesh geometry={nodes.SK_Leg_Lower_Hi_Dark_Mat_0_1.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Leg_Lower_Hi_Wires_Mat1_0_1.geometry} material={materials.Wires_Mat1} />
            <mesh geometry={nodes.SK_Leg_Lower_Hi_Body_Mat_0_1.geometry} material={materials.Body_Mat} />
            <mesh geometry={nodes.SK_Foot_Hi_Rubber_Mat_0_1.geometry} material={materials.Rubber_Mat} />
            <mesh geometry={nodes.SK_Foot_Hi_Dark_Mat_0_1.geometry} material={materials.Dark_Mat} />
            <mesh geometry={nodes.SK_Foot_Hi_Kashima_Mat_0_1.geometry} material={materials.Kashima_Mat} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
